:PROPERTIES:
:ID:       95db6034-1363-4e72-bb17-5e5f8f729397
:END:
#+title: shivambu

Shivambu (auto- urine) is heavenly nectar, which is capable of destroying senility and diseases. The practitioner of Yoga should take it before proceeding with his other rituals.
After cleansing the mouth, and performing the other essential morning functions, one should drink one’s own clear urine, which is the annihilator of senility and diseases.
One who drinks Shivambu for the duration of a month will be purified internally. Drinking it for two months stimulates and energizes the senses.
Drinking it for three months destroys all diseases and frees one from all troubles. By drinking it for five months, one acquires divine vision and freedom from all diseases.
Continuation of the practice for six months makes the practitioner highly intelligent and proficient in the scriptures, and if the duration is seven months, the practitioner acquires extraordinary strength.
If the practice is continued for eight months, one acquires a permanent glow like that of gold, and if it is continued for nine months, one is freed from tuberculosis and leprosy.
Ten months of this practice makes one a veritable treasury of luster. Eleven months of it would purify all the organs of the body.
A man who has continued the practice for a year becomes the equal of the sun in radiance. He who has continued for two years conquers the element Earth.
If the practice is continued for three years, one conquers the element of Water, and if it is continued for four years, the element Light is also conquered.
He who continues the practice for five years conquers the element Air, and he who continues it for seven years conquers pride.
Continuation of the practice for eight years enables one to conquer all the important elements of Nature, and continuation of it for nine years frees one from the cycle of birth and death.
One who has continued the practice for ten years can fly through the air without effort. One who has continued it for eleven years is able to hear the voice of his sour (inner self)
He who has continued the practice for twelve years will live so long as the moon and the stars last. He is not troubled by dangerous animals such as snakes, and no poisons can kill him. He cannot be consumed by fire, and can float on water just like wood.
