:PROPERTIES:
:ID:       75fa29e7-7c2b-459d-9dfa-0626df4f5d00
:END:
#+title: Castaneda

They say that they were very likable but extremely scary. They were more like unknown creatures. What makes mankind homogeneous is the fact that we are all luminous balls. And those sorcerers were no longer balls of energy but lines of energy that were trying to bend themselves into circles, which they couldn't quite make."

"What finally happened to them, don Juan? Did they die?"

"Sorcerers' stories say that because they had succeeded in stretching their shapes, they had also succeeded in stretching the duration of their consciousness. So they are alive and conscious to this day. There are stories about their periodic appearances on the earth."

"What do you think of all this yourself, don Juan?"

"It is too bizarre for me. I want freedom. Freedom to retain my awareness and yet disappear into the vastness. In my personal opinion, those old sorcerers were extravagant, obsessive, capricious men who got pinned down by their own machinations. [* machination- a crafty and involved plot to achieve your (usually sinister) ends]

"But don't let my personal feelings sway you. The old sorcerers' accomplishment is unparalleled. If nothing else, they proved to us that man's potentials are nothing to sneeze at."
