:PROPERTIES:
:ID:       75fa29e7-7c2b-459d-9dfa-0626df4f5d00
:END:
#+title: Castaneda

They say that they were very likable but extremely scary. They were more like unknown creatures. What makes mankind homogeneous is the fact that we are all luminous balls. And those sorcerers were no longer balls of energy but lines of energy that were trying to bend themselves into circles, which they couldn't quite make."

"What finally happened to them, don Juan? Did they die?"

"Sorcerers' stories say that because they had succeeded in stretching their shapes, they had also succeeded in stretching the duration of their consciousness. So they are alive and conscious to this day. There are stories about their periodic appearances on the earth."

"What do you think of all this yourself, don Juan?"

"It is too bizarre for me. I want freedom. Freedom to retain my awareness and yet disappear into the vastness. In my personal opinion, those old sorcerers were extravagant, obsessive, capricious men who got pinned down by their own machinations. [* machination- a crafty and involved plot to achieve your (usually sinister) ends]

"But don't let my personal feelings sway you. The old sorcerers' accomplishment is unparalleled. If nothing else, they proved to us that man's potentials are nothing to sneeze at."

** The Sorcer-Warrior
The path of knowledge is a forced one. In order to learn we must be spurred. In the path of knowledge we are always fighting something, avoiding something, prepared for something; and that something is always inexplicable, greater, more powerful than us. The inexplicable forces will come to you.

The world is indeed full of frightening things and we are helpless creatures surrounded by forces that are inexplicable and unbending. The average man, in ignorance, believes that those forces can be explained or changed; he doesn't really know how to do that, but he expects that the actions of mankind will explain them or change them sooner or later. The sorcerer, on the other hand, does not think of explaining or changing them; instead, he learns to use such forces by redirecting himself and adapting to their direction. That's his trick. There is very little to sorcery once you find out its trick. A sorcerer is only slightly better off than the average man. Sorcery does not help him to live a better life; in fact I should say that sorcery hinders him; it makes his life cumbersome, precarious. By opening himself to knowledge a sorcerer becomes more vulnerable than the average man. On the one hand his fellow men hate him and fear him and will strive to end his life; on the other hand the inexplicable and unbending forces that surround every one of us, by right of our being alive, are for a sorcerer a source of even greater danger. To be pierced by a fellow man is indeed painful, but nothing in comparison to being touched by an [inorganic] ally. A sorcerer, by opening himself to knowledge, falls prey to such forces and has only one means of balancing himself, his will; thus he must feel and act like a warrior. I will repeat this once more: Only as a warrior can one survive the path of knowledge. What helps a sorcerer live a better life is the strength of being a warrior.

It is my commitment to teach you to *see*. Not because I personally want to do so but because you were chosen; you were pointed out to me [...] I am compelled by my personal desire, however, to teach you to feel and act like a warrior. I personally believe that to be a warrior is more suitable than anything else. Therefore I have endeavored to show you those forces as a sorcerer perceives them, because only under their terrifying impact can one become a warrior. To see without first being a warrior would make you weak; it would give you a false meekness, a desire to retreat; your body would decay because you would become indifferent. It is my personal commitment to make you a warrior so you won't crumble.

I have heard you say time and time again that you are always prepared to die. I don't regard that feeling as necessary. I think it is a useless indulgence. A warrior should be prepared only to battle. I have also heard you say that your parents injured your spirit. I think the spirit of man is something that can be injured very easily, although not by the same acts you yourself call injurious. I believe that your parents did injure you by making you indulgent and soft and given to dwelling.

The spirit of a warrior is not geared to indulging and complaining, nor is it geared to winning or losing. The spirit of a warrior is geared only to struggle, and every struggle is a warrior's last battle on earth. Thus the outcome matters very little to him. In his last battle on earth a warrior lets his spirit flow free and clear. And as he wages his battle, knowing that his will is impeccable, a warrior laughs and laughs.

~ Carlos Castaneda - A Separate Reality


** Cutoff times
From https://www.youtube.com/watch?v=X5MlVq8Jl0s
Part 1: 31:03

Note: How to add chapters to ogg
https://stackoverflow.com/questions/49364269/how-to-add-chapters-to-ogg-file


