
:PROPERTIES:
:ID:       fe4a38b5-3054-4474-8ac5-e64a442320de
:END:
#+title: astrology

* Moon
** Combust hours
#+begin_quote
"Some of the ancient sages, from whom I do not wish to deviate, said
that after the conjunction of the Sun and Moon, from the very minute
of their conjunction, there are 12 hours which are called “combust”;
and after those 12 combust hours are 72 hours which are called
“incombust”; and after those 72 incombust ones are 12 combust ones;
and so on up to the degree and minute of the next conjunction that
follows. And they said that the 12 combust hours are divided into
three equal parts, by giving to each part four of these hours. And
they said that he who prepares to make war in the first four hours, or
goes to war, ought to fear the death of his body. And he who prepares
in the second four hours to make war, or goes to war, should fear for
his capture, or being wounded, or some blow, [but] without losing his
life. And he who undertakes in the last four hours to make war,or goes
to war, should fear the loss of his substance and of those who were
with him; and he could even lose the persons who help him. And he who
undertakes to plow in the first four hours, or goes to plow, should
fear the loss of the fruits of his hope from that plowing. And he who
undertakes to plow in the second four hours, or who goes to plow,
should fear great detriment in all things that he possesses, and even
in his body, [but] without losing his life. And he who undertakes to
plow in the last four"
~ Bonatti, On Mundane Astrology
#+end_quote


## Lunar Zodiac
30 may 2023 Lunar point of Aries at 5 degrees 39 minutes Libra.


## Purva Badra
 Lord Hanuman is said to have been born in this constellation. Purva
 Bhadra is extremely intelligent and yet an unbiased, simple and
 peace-loving energy.

The faith in God is complete in this constellation. All that is
supernatural is of great interest to the natives of this
constellation. The pure heart emerging from this constellation enables
access to the ethereal dimensions of life more than to the
mundane. The character of Purva Bhadra is one of bona fide. The
natives are generally of good reputation. They cherish speaking the
truth and try to be truthful. They distance themselves from cheap
tricks of manipulation and dishonesty. They are optimistic and always
benevolent and helpful to others. Friendliness, love and affection are
their natural qualities. They pour their heart’s energies into every
work that they do; they are not careless or inattentive.

They do well in spirituality. They are fairly good in studies relating
to astrology, astronomy, occult sciences and normal sciences. In terms
of earning money and living in society, they believe in simplicity and
are honourable. They prefer to be self-employed, for they do not find
a boss or a superior virtuous enough to serve.

Purva Bhadra is a protective constellation. It gives an anterior
protection and anterior shelter, while Uttara Bhadra gives a posterior
shelter and protection.

An anterior shelter is a protection that is ahead of you. It means,
the natives of this constellation offer shelter and protection to
those who follow them. Lord Hanuman was always moving ahead of Lord
Rama to ensure complete protection to Lakshmana and Sita. In fact,
Hanuman is an embodiment of protection for all those who worship
him. The beauty of Purva Bhadra is that it is ruled by Jupiter, the
preceptor and also the Lord. Thursdays are very propitious to the
natives of this constellation.

The cosmic deity of this constellation is Lord Shiva, who constitutes
the Jupiter for the universe. The seer is Agastya, who is an
embodiment of Lord Shiva.

The single-horned unicorn, the one-footed serpent (the serpent of
Kundalini), the unitary symbol Shiva Lingam (Ekapada), who is also
called the unborn one (Aja), are but symbols relating to Purva Bhadra.

The worship of Shiva or Hanuman enables the natives of Purva Bhadra to
ensure auspiciousness ahead of them. Purva Bhadra natives are also
considered to be lucky-footed ones. It is but natural that when a
Sadguru (seer) or Lord Shiva or Hanuman step in, things turn out to be
auspicious. The number relating to Purva Bhadra is 7, the colour is
golden yellow or silver grey, the gemstone is a yellow sapphire, the
favourable number is 3, the fruit is mango, the tree is neem, the
element is ether, the bird is a peacock, and the animal is a lion.

Jupiter being the presiding deity and planet, education, intelligence,
wealth, expansion are but very common for the natives of Purva
Bhadra. Their knowledge precedes their wealth. Their preference is
also more towards knowledge than towards wealth.

Since they are ruled by Ekapada, the single-footed deity, they would
eventually be raised by a single parent. In the human body they
represent the right brain as also the thighs and the legs.

The natives of Purva Bhadra are well balanced in their abstract
thinking and practical working. Purva Bhadra natives mature in all
dimensions of life earlier than their age. Since they are sky loving
ones, they do not hold a permanent abode on Earth. They keep
moving. They learn sciences and practice them. They are intuitive and
goodwill-oriented. Being Jupiterians, they are good orators and also
have sound sleep. They are adventurous and brave individuals and are
driven by the purpose. They love mysticism and occult practices.

The Purva Bhadra natives are medium sized and have broad cheeks and
fleshy lips. They look simple.

They are principled and therefore suffer mentally.

They care not for their attire. They also care not for blind
beliefs. They are respected and honoured in the society. They love
food. They have smiling eyes and pleasing personality. They evolve
their own program of self-development and do not carry the sheep-like
mentality. They approach life with freshness along with the support of
knowledge. The daylily plant represents their vibrant, fresh and
powerful personality.

## Hasta Hasta is the constellation of manifestation. Hasta means

“hand”. The natives of this constellation are dexterous with their
hands. Any art or science involving the use of hands is best suited to
the natives of Hasta. They tend to be very good healers and
cooks. They have a very good hand and mind coordination. Their mind is
also full of enthusiasm to work. With the related intuition, they can
work out magical manifestations.

They have one-pointed attention and concentration.

The Moon is the ruler of the constellation. The Hasta moon is open,
receptive, and develops an intuitive understanding. The Hasta natives
are flexible and adaptable. They relate well to ground realities. On
the surface, they seem to be very confident but suffer insecurity
within their being.

The lord of the constellation is Savitr, the Central Sun, and the
mantra best suited for them is Gayatri.  The unique feature of Hasta
is that the natives do not get involved in challenges and fights. They
do not engage in debates and discussions; they feel such an activity
is a waste of time. There is an anecdote in this regard. Once a giant
(a diabolic one) challenges the Sun to fight with him or accept
defeat. The Sun smilingly replied, “I may be defeated or I may be
defeating you, either way I have no interest. I have work to do, which
I would not like to set aside for fights and challenges.”

This attitude is the beauty of Hasta.

Since this constellation constitutes the central theme of Virgo, the
natives are endowed with purity of thought. Their hands are clean, in
the sense that they do not involve in unlawful activity. Their
inspiration is the Central Sun whose energy they receive from the head
unto their palms. They perform well and are generally contended. They
are light and swift. The hands in the human body represent
Hasta. While the number is 13, the favourable number is 2. Since
number 2 is the number of the Moon, they have cool and calm
nature. Number 13, being a number of conflicts, they are surrounded
always by conflicting situations. The beauty of the natives of Hasta
is that they smile away their difficulties and do not succumb to the
hardships of life. They remain simple, quiet and cool with much
patience springing from within.

The Hasta natives catch cold and cough with every weather change.

Hasta consists of five stars and looks like an elephant head with its
trunk. For this reason, the elephant-headed god is related to this
constellation and is specially worshipped. When the Sun is in Virgo
and the Moon is in Hasta constellation, Ganesha, the elephant-headed
deity, is worshipped all over India to derive the benefits of the
constellation. Ganesha is a deity with all-round virtues and it is
seen as the cosmic son of the virgin, the World Mother. He bestows
energies to fulfil oneself. He rounds up the angularities of
personality and ensures all-round development. He is also seen as
Cosmic Jupiter and all that relates to Jupiterian energy. The natives
of Hasta would do well by worshipping Ganesha, besides contemplating
upon Gayatri. The Moon visits Hasta every month and that has to be
particularly noted to relate to Ganesha for self-fulfilment.

The natives of Hasta are resourceful, pleasant and practical. The
animal symbol relating to Hasta is the elephant head.

The colour is light green, since Mercury also shines forth in this
constellation besides the Moon. The tree relating to this
constellation is hog-plum (maredu), considered as one of the most
sacred trees in the Vedic order. The body parts are the lateral
sides. The stone is topaz. The bird is a vulture. The animal is a
female buffalo.

The natives of Hasta would do well to consume the neem herb from time
to time to set their stomachs in good order.

Hasta also means “the smiling one”. “Has” in Sanskrit means smile. The
natives of Hasta generally carry a smile on their countenance and make
light of the life situations. Hasta is considered to be a levelling
nakshatra, meaning, it flourishes well on the plane land compared to
mountain regions. They can be good agriculturalists and
traders. Light-hearted work suits them. Since the Moon is the ruler,
Hasta natives have waxing and waning moods. Because Mercury is another
ruler, they have the knack of discriminating and avoiding conflictive
situations. The Hasta native can be a good handy person who delivers
well by receiving the instructions. They are masters of manifestation
but they require guidance.

Number 13, though conflicting by nature, is seen as the number
associated with occult subjects. Hasta natives generally are
comfort-oriented and quiet performers in the world. However, if their
inclination turns inward, they would quickly gain an understanding of
the intricacies of the esoteric science.

Swami Vivekananda, the famous Indian saint, was born in this
constellation. He impacted the globe with the inner dimension of Vedic
Philosophy.

On a lighter vein, Hasta natives’ dexterity with the hand can make
them good pickpockets, card players, and casino dealers. They are good
with a “sleight of hand”. They can be good sculptors, masons and so
on.

